import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, Toolbar } from "@mui/material";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VYASA MEDIA NETWORK",
  description: "Generated by create next app",
  icons: './logo.jpeg'

};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <Box>
        <Toolbar />
        {children}
      </Box>
      <Footer />
    </>
  );
}
